on:
  push:
    branches:
      - main
      - integration_tests
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.18.3-bullseye ]
    runs-on: ubuntu-22.04
    container: golang:${{ matrix.containers }}
    env:
      VAULT_TOKEN: vaultpwd
      VAULT_ADDR: http://localhost:8200
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        run: go test -v -race -timeout=60s ./...
      - run: >
          curl --fail -H "X-Vault-Token: vaultpwd"
          http://localhost:8200/v1/sys/health
    services:
      vault:
        image: vault:1.10.3
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: vaultpwd
